services:
  login-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vyartha-login-backend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vyartha-login.rule=Host(`vyartha-login.ratival.com`)"
      - "traefik.http.routers.vyartha-login.entrypoints=websecure"
      - "traefik.http.routers.vyartha-login.tls=true"
      - "traefik.http.services.vyartha-login.loadbalancer.server.port=3000"
